"use client";
import { useMemo, useState } from "react";
import { ArrowUpDown, MoreHorizontal, Plus, Search, Users } from "lucide-react";
import { createColumnHelper, flexRender, rowSortingFeature, createSortedRowModel, tableFeatures, useTable } from "@tanstack/react-table";
import { Badge, Button, Card } from "@/components/ui";

type Applicant = { name:string; role:string; date:string; status:"Baru"|"Ditinjau"|"Interview"|"Diterima"|"Ditolak" };
const rows:Applicant[]=[{name:"Alya Putri",role:"Senior Product Designer",date:"21 Sep 2026",status:"Baru"},{name:"Bima Pratama",role:"Senior Product Designer",date:"20 Sep 2026",status:"Ditinjau"},{name:"Citra Lestari",role:"Frontend Engineer",date:"19 Sep 2026",status:"Interview"},{name:"Dimas Arya",role:"Data Analyst",date:"18 Sep 2026",status:"Diterima"}];
const features=tableFeatures({rowSortingFeature,sortedRowModel:createSortedRowModel()});
const helper=createColumnHelper<typeof features, Applicant>();

export default function RecruiterDashboard(){ const [status,setStatus]=useState("Semua"); const filtered=useMemo(()=>rows.filter(r=>status==="Semua"||r.status===status),[status]); const columns=useMemo(()=>helper.columns([helper.accessor("name",{header:"KANDIDAT",cell:({row})=><div className="candidate-cell"><span className="company-avatar">{row.original.name[0]}</span><strong>{row.original.name}<small>{row.original.role}</small></strong></div>}),helper.accessor("date",{header:({column})=><button className="table-sort" onClick={()=>column.toggleSorting(column.getIsSorted()==="asc")}>TANGGAL <ArrowUpDown size={13}/></button>}),helper.accessor("status",{header:"STATUS",cell:({getValue})=><Badge tone={getValue()==="Diterima"?"green":getValue()==="Baru"?"blue":getValue()==="Ditolak"?"orange":"slate"}>{String(getValue())}</Badge>}),helper.display({id:"actions",header:"",cell:()=> <button className="table-more"><MoreHorizontal size={16}/></button>})]),[]); const table=useTable({data:filtered,columns,features}); return <main className="recruiter-shell"><aside className="recruiter-side"><span className="pro-eyebrow">RECRUITER WORKSPACE</span><h2>Nexa Labs</h2><button className="recruiter-nav active">▦ Overview</button><button className="recruiter-nav">▤ Lowongan saya</button><button className="recruiter-nav">♙ Kandidat</button><button className="recruiter-nav">⚙ Pengaturan</button></aside><section className="recruiter-content"><div className="recruiter-heading"><div><span className="pro-eyebrow">MONDAY, 21 SEPTEMBER 2026</span><h1>Selamat pagi, Nadia.</h1><p className="page-lead">Kelola proses hiring dan temukan talenta terbaik untuk timmu.</p></div><Button><Plus size={16}/> Buat lowongan</Button></div><div className="recruiter-stats"><Card><Users size={18}/><small>Total kandidat</small><strong>220</strong><span>+18% bulan ini</span></Card><Card><Users size={18}/><small>Lowongan aktif</small><strong>4</strong><span>2 perlu perhatian</span></Card><Card><Users size={18}/><small>Interview minggu ini</small><strong>12</strong><span>3 hari ini</span></Card></div><Card className="recruiter-table-card"><div className="table-toolbar"><div><h2>Pelamar terbaru</h2><p>Kelola kandidat dari semua lowongan aktif.</p></div><div className="table-controls"><div className="table-search"><Search size={15}/><input placeholder="Cari kandidat..." /></div><select value={status} onChange={(e)=>setStatus(e.target.value)} aria-label="Filter status"><option>Semua</option><option>Baru</option><option>Ditinjau</option><option>Interview</option><option>Diterima</option><option>Ditolak</option></select></div></div><div className="pro-table"><div className="pro-tr pro-th"><span>KANDIDAT</span><span>TANGGAL</span><span>STATUS</span><span></span></div>{table.getRowModel().rows.map(row=><div className="pro-tr" key={row.id}>{row.getAllCells().map(cell=><span key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</span>)}</div>)}</div></Card></section></main> }
