"use client";
import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Search, Users } from "lucide-react";
import { Badge, Button, Card } from "@/components/ui";

type Status = "new" | "reviewed" | "interview" | "accepted" | "rejected";
type Applicant = { id: string; status: Status; created_at: string; profiles?: { name?: string; email?: string } | null; jobs?: { title?: string } | null };
const labels: Record<Status, string> = { new: "Baru", reviewed: "Ditinjau", interview: "Interview", accepted: "Diterima", rejected: "Ditolak" };
const tone = (status: Status) => status === "accepted" ? "green" : status === "new" ? "blue" : status === "rejected" ? "orange" : "slate";

export default function RecruiterLiveDashboard() {
  const [applications, setApplications] = useState<Applicant[]>([]); const [filter, setFilter] = useState<Status | "all">("all"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState<string | null>(null);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/recruiter/applications", { cache: "no-store" }); const result = await response.json() as { applications?: Applicant[]; error?: string }; if (!response.ok) throw new Error(result.error ?? "Pelamar gagal dimuat"); setApplications(result.applications ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Pelamar gagal dimuat"); } finally { setLoading(false); } }
  useEffect(() => {
    // Initial fetch intentionally synchronizes remote server state.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, []);
  async function updateStatus(id: string, status: Status) { setUpdating(id); setError(""); try { const response = await fetch("/api/recruiter/applications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ applicationId: id, status }) }); const result = await response.json() as { application?: { id: string; status: Status }; error?: string }; if (!response.ok) throw new Error(result.error ?? "Status gagal diperbarui"); setApplications((current) => current.map((item) => item.id === id ? { ...item, status: result.application?.status ?? status } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Status gagal diperbarui"); } finally { setUpdating(null); } }
  const filtered = useMemo(() => applications.filter((item) => (filter === "all" || item.status === filter) && `${item.profiles?.name ?? ""} ${item.jobs?.title ?? ""}`.toLowerCase().includes(search.toLowerCase())), [applications, filter, search]);
  const counts = applications.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + 1; return acc; }, {});
  return <main className="recruiter-shell"><aside className="recruiter-side"><span className="pro-eyebrow">RECRUITER WORKSPACE</span><h2>Recruiter</h2><span className="recruiter-nav active">▦ Kandidat</span><span className="recruiter-nav">▤ Lowongan saya</span></aside><section className="recruiter-content"><div className="recruiter-heading"><div><span className="pro-eyebrow">LIVE DATA</span><h1>Pipeline kandidat</h1><p className="page-lead">Kelola pelamar dari lowongan milikmu.</p></div><Button onClick={() => void load()} disabled={loading}><RefreshCw size={15}/> Refresh</Button></div><div className="recruiter-stats"><Card><Users size={18}/><small>Total kandidat</small><strong>{applications.length}</strong></Card><Card><Users size={18}/><small>Interview</small><strong>{counts.interview ?? 0}</strong></Card><Card><Users size={18}/><small>Diterima</small><strong>{counts.accepted ?? 0}</strong></Card></div><Card><div className="table-toolbar"><div className="search-control"><Search size={15}/><input aria-label="Cari kandidat" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari kandidat..." /></div><select aria-label="Filter status" value={filter} onChange={(event) => setFilter(event.target.value as Status | "all")}><option value="all">Semua status</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{error && <p className="field-error" role="alert">{error}</p>}{loading ? <div className="skeleton-card" aria-label="Memuat pelamar"/> : filtered.length === 0 ? <div className="empty-state"><Users size={24}/><strong>Belum ada pelamar</strong><p>Pelamar pada lowonganmu akan muncul di sini.</p></div> : <div className="applicant-table"><div className="applicant-row applicant-head"><span>KANDIDAT</span><span>LOWONGAN</span><span>TANGGAL</span><span>STATUS</span></div>{filtered.map((item) => <div className="applicant-row" key={item.id}><div><strong>{item.profiles?.name ?? "Kandidat"}</strong><small>{item.profiles?.email ?? "Email privat"}</small></div><span>{item.jobs?.title ?? "Lowongan"}</span><span>{new Date(item.created_at).toLocaleDateString("id-ID")}</span><div className="status-action"><Badge tone={tone(item.status)}>{labels[item.status]}</Badge><select disabled={updating === item.id} aria-label={`Ubah status ${item.profiles?.name ?? "kandidat"}`} value={item.status} onChange={(event) => void updateStatus(item.id, event.target.value as Status)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div>)}</div>}</Card></section></main>;
}
