"use client";
import { useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { UploadCloud, FileText, X, Send } from "lucide-react";
import { applicationMetadataSchema } from "@/lib/schemas";
import { z } from "zod";
import { Button, Card } from "@/components/ui";
type FormValues=z.input<typeof applicationMetadataSchema>;
export default function ApplyPage(){const params=useSearchParams();const jobId=params.get("job")??"";const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [serverError,setServerError]=useState("");const [success,setSuccess]=useState(false);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormValues>({resolver:zodResolver(applicationMetadataSchema),defaultValues:{jobId,coverLetter:""}});async function submit(values:FormValues){setServerError("");setSuccess(false);if(!z.string().uuid().safeParse(values.jobId).success){setServerError("Lowongan tidak valid. Buka form dari halaman detail lowongan.");return}if(!file){setServerError("CV wajib diunggah dalam format PDF");return}const body=new FormData();body.set("jobId",values.jobId);body.set("coverLetter",values.coverLetter??"");body.set("cv",file);const response=await fetch("/api/applications",{method:"POST",body});const result=await response.json() as {error?:string};if(!response.ok){setServerError(result.error??"Lamaran gagal dikirim");return}setSuccess(true)}return <main className="pro-page apply-page"><span className="pro-eyebrow">LAMAR PEKERJAAN</span><h1>Kirim lamaranmu.</h1><p className="page-lead">Lamaran akan dikirim ke lowongan yang kamu pilih.</p><form className="apply-layout" onSubmit={handleSubmit(submit)}><Card><h2>Dokumen lamaran</h2><p className="form-help">CV membantu recruiter mengenal pengalamanmu lebih jauh.</p><input type="hidden" {...register("jobId")}/><button type="button" className={`dropzone ${file?"has-file":""}`} onClick={()=>inputRef.current?.click()} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();const dropped=e.dataTransfer.files[0];if(dropped)setFile(dropped)}}><input ref={inputRef} hidden type="file" accept="application/pdf" onChange={(e)=>setFile(e.target.files?.[0]??null)}/>{file?<><FileText size={26}/><strong>{file.name}</strong><small>{Math.round(file.size/1024)} KB · PDF</small></>:<><UploadCloud size={28}/><strong>Upload CV kamu</strong><small>Drag & drop atau klik untuk memilih · PDF, maks. 5MB</small></>}</button>{file&&<button type="button" className="remove-file" onClick={()=>setFile(null)}><X size={14}/> Hapus file</button>}<label className="pro-label" htmlFor="coverLetter">Cover letter <span>Opsional</span></label><textarea id="coverLetter" className="pro-textarea" {...register("coverLetter")} placeholder="Ceritakan secara singkat mengapa kamu cocok..." />{errors.coverLetter&&<small className="field-error">{errors.coverLetter.message}</small>}</Card><Card className="apply-side"><h3>Ringkasan lamaran</h3><p className="form-help">Job ID: {jobId||"belum dipilih"}</p>{serverError&&<p className="field-error" role="alert">{serverError}</p>}{success&&<p className="success-message" role="status">Lamaran berhasil dikirim.</p>}<Button type="submit" disabled={isSubmitting||!jobId}>{isSubmitting?"Mengirim...":<>Kirim lamaran <Send size={15}/></>}</Button></Card></form></main>}
