import type { ReactNode, ButtonHTMLAttributes, InputHTMLAttributes } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Check, Sparkles } from "lucide-react";

export function Button({ children, variant = "primary", className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "success" }) {
  return <button className={`ui-button ui-button-${variant} ${className}`} {...props}>{children}</button>;
}
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`ui-card ${className}`}>{children}</div>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="ui-input" {...props} />; }
export function Badge({ children, tone = "blue" }: { children: ReactNode; tone?: "blue" | "green" | "orange" | "slate" }) { return <span className={`ui-badge ui-badge-${tone}`}>{children}</span>; }
export function ThemeToggle() { return <button className="theme-toggle" aria-label="Ganti tema" type="button">◐</button>; }
export function Brand() { return <Link href="/" className="pro-brand"><span className="pro-brand-icon"><Sparkles size={15} /></span><span>jobprep<span className="pro-brand-dot">.</span></span></Link>; }
export function JobCard({ job }: { job: { id: string; title: string; company: string; location: string; type: string; level: string; industry: string; description: string } }) { return <Card className="job-pro-card"><div className="job-card-top"><span className="company-avatar">{job.company[0]}</span><Badge tone="green">Baru</Badge></div><h3>{job.title}</h3><p className="job-company">{job.company}</p><p className="job-description">{job.description}</p><div className="job-meta"><span>⌖ {job.location}</span><span>◷ {job.type}</span><span>◈ {job.level}</span></div><Link href={`/jobs/${job.id}`} className="job-card-link">Lihat detail <ArrowRight size={15} /></Link></Card>; }
export function InterviewQuestionCard({ category, question, step, total }: { category: string; question: string; step: number; total: number }) { return <motion.div key={`${step}-${question}`} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .22, ease: "easeOut" }}><Card className="question-card"><div className="question-progress"><span>Pertanyaan {step} dari {total}</span><strong>{Math.round((step / total) * 100)}%</strong></div><div className="progress-track"><span style={{ width: `${(step / total) * 100}%` }} /></div><Badge tone="blue">{category}</Badge><h2>{question}</h2><p className="question-helper">Jawab seolah-olah kamu sedang berada di interview sebenarnya. Gunakan contoh yang spesifik.</p></Card></motion.div>; }
export function FeedbackCard({ score = 4.2 }: { score?: number }) { return <Card className="feedback-card"><div className="feedback-heading"><span className="feedback-icon"><Sparkles size={18} /></span><div><h3>Feedback dari asisten AI</h3><p>Analisis jawabanmu sudah selesai</p></div><strong>{score}<small>/5</small></strong></div><div className="feedback-columns"><div><b><Check size={14} /> Kekuatan</b><p>Jawaban relevan dan menyertakan konteks yang jelas.</p></div><div><b><ArrowRight size={14} /> Saran berikutnya</b><p>Tambahkan hasil yang terukur untuk memperkuat dampak.</p></div></div></Card>; }
export function ScoreSummary() { return <Card className="score-summary"><div className="score-visual"><strong>4.2</strong><span>/5</span><small>Skor kesiapan</small></div><div><Badge tone="green">Progress bagus</Badge><h3>Kamu semakin siap.</h3><p>Struktur jawabanmu sudah kuat. Fokus berikutnya adalah memperjelas hasil dan dampak.</p><div className="summary-check"><Check size={15} /> Relevansi jawaban <strong>4.5/5</strong></div><div className="summary-check"><Check size={15} /> Kejelasan komunikasi <strong>4.0/5</strong></div></div></Card>; }
export function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="pro-section-heading"><span className="pro-eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
