"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { JobCard, Card } from "@/components/ui";
type Job={id:string;title:string;description:string;location:string;work_type:string;level:string;industry:string;companies?:{name:string}|null};
const display=(job:Job)=>({id:job.id,title:job.title,company:job.companies?.name??"Perusahaan",location:job.location,type:job.work_type,level:job.level,industry:job.industry,description:job.description});
export default function JobsPage(){const [jobs,setJobs]=useState<Job[]>([]);const [search,setSearch]=useState("");const [location,setLocation]=useState("");const [level,setLevel]=useState("");const [workType,setWorkType]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const query=useMemo(()=>new URLSearchParams({...(search?{search}:{}),...(location?{location}:{}),...(level?{level}:{}),...(workType?{workType}:{})}).toString(),[search,location,level,workType]);useEffect(()=>{let active=true;
    // Loading state begins a remote synchronization for the current query.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true);fetch(`/api/jobs?${query}`).then(async(response)=>{const result=await response.json() as {jobs?:Job[];error?:string};if(!response.ok)throw new Error(result.error??"Lowongan gagal dimuat");if(active)setJobs(result.jobs??[])}).catch((caught)=>{if(active)setError(caught instanceof Error?caught.message:"Lowongan gagal dimuat")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query]);return <main className="pro-page"><div className="listing-heading"><div><span className="pro-eyebrow">PELUANG UNTUKMU</span><h1>Temukan lowongan berikutnya.</h1><p>Lowongan aktif dari database JobPrep.</p></div><button className="ui-button ui-button-secondary mobile-filter"><SlidersHorizontal size={16}/> Filter</button></div><div className="listing-search"><Search size={18}/><input aria-label="Cari lowongan" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Cari jabatan, perusahaan, atau skill..."/><button className="ui-button ui-button-primary" type="button">Cari</button></div><div className="listing-layout"><aside className="filter-panel"><div className="filter-heading"><b>Filter lowongan</b><button type="button" onClick={()=>{setSearch("");setLocation("");setLevel("");setWorkType("")}}>Reset</button></div><label>Lokasi<select value={location} onChange={(e)=>setLocation(e.target.value)}><option value="">Semua lokasi</option><option>Jakarta</option><option>Bandung</option></select></label><label>Level<select value={level} onChange={(e)=>setLevel(e.target.value)}><option value="">Semua level</option><option value="entry">Entry</option><option value="mid">Mid</option><option value="senior">Senior</option><option value="lead">Lead</option></select></label><label>Tipe kerja<select value={workType} onChange={(e)=>setWorkType(e.target.value)}><option value="">Semua tipe</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select></label></aside><section className="listing-results"><div className="results-head"><span><b>{loading?"—":jobs.length}</b> lowongan ditemukan</span></div>{loading?<div className="skeleton-grid"><div className="skeleton-card"/><div className="skeleton-card"/></div>:error?<Card><h3>Lowongan belum tersedia</h3><p className="field-error">{error}</p></Card>:jobs.length?<div className="job-list">{jobs.map((job)=><JobCard key={job.id} job={display(job)}/>)}</div>:<Card><h3>Belum ada hasil</h3><p>Coba ubah kata kunci atau filter.</p></Card>}</section></div></main>}
